import {test} from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {DatabaseSync} from 'node:sqlite';
import {generateKeyPair,SignJWT} from 'jose';
import {authRoute,authenticatedUser,tokenHash,verifyGoogleToken} from '../server/auth.js';
import {d1Adapter} from '../server/local-d1.mjs';
import worker from '../server/worker.js';
function setup(){const db=new DatabaseSync(':memory:');for(const f of fs.readdirSync('drizzle').filter(f=>f.endsWith('.sql')))db.exec(fs.readFileSync('drizzle/'+f,'utf8'));return {db,env:{DB:d1Adapter(db),GOOGLE_CLIENT_ID:'test-client',GOOGLE_CLIENT_SECRET:'test-secret'}};}
const req=(path,headers={},method='GET')=>new Request('https://app.test'+path,{headers,method});
test('profile photos save and load through D1 without paid object storage',async()=>{const {db,env}=setup(),token='c'.repeat(64),avatar='data:image/jpeg;base64,/9j/2Q==';db.prepare('INSERT INTO sessions VALUES (?,?,?,?)').run(await tokenHash(token),'alice','alice@example.test',Date.now()+60000);const headers={Cookie:'__Host-nte-session='+token,Origin:'https://app.test','Content-Type':'application/json'};const save=await worker.fetch(new Request('https://app.test/api/profile',{method:'POST',headers,body:JSON.stringify({profile:{name:'Proxy',avatar},revision:0})}),env,{});assert.equal(save.status,200);assert.equal((await save.json()).profile.avatar,avatar);const reload=await worker.fetch(req('/api/state',headers),env,{});assert.equal((await reload.json()).profile.avatar,avatar);assert.equal(db.prepare('SELECT COUNT(*) AS count FROM avatar_images').get().count,1);const remove=await worker.fetch(new Request('https://app.test/api/profile',{method:'POST',headers,body:JSON.stringify({profile:{name:'Proxy',avatar:''},revision:1})}),env,{});assert.equal(remove.status,200);assert.equal(db.prepare('SELECT COUNT(*) AS count FROM avatar_images').get().count,0);});
test('only unexpired hashed session cookies authenticate users',async()=>{const {db,env}=setup(),token='a'.repeat(64),hash=await tokenHash(token);assert.equal(await authenticatedUser(req('/',{'oai-authenticated-user-id':'alice'}),env),null);db.prepare('INSERT INTO sessions VALUES (?,?,?,?)').run(hash,'google:alice','alice@example.test',Date.now()+60000);assert.deepEqual(await authenticatedUser(req('/',{Cookie:'__Host-nte-session='+token}),env),{id:'google:alice',email:'alice@example.test'});db.prepare('UPDATE sessions SET expires_at=0').run();assert.equal(await authenticatedUser(req('/',{Cookie:'__Host-nte-session='+token}),env),null);});
test('Google authorization binds PKCE, nonce and expiring state to an HttpOnly cookie',async()=>{const {db,env}=setup(),res=await authRoute(req('/auth/google'),env),url=new URL(res.headers.get('Location')),state=url.searchParams.get('state'),row=db.prepare('SELECT * FROM oauth_states').get();assert.equal(res.status,303);assert.match(res.headers.get('Set-Cookie'),/Secure; HttpOnly; SameSite=Lax/);assert.equal(row.state_hash,await tokenHash(state));assert.equal(row.nonce,url.searchParams.get('nonce'));assert.equal(url.searchParams.get('code_challenge_method'),'S256');assert.equal(url.searchParams.get('redirect_uri'),'https://app.test/auth/google/callback');assert.equal(url.searchParams.get('scope'),'openid email profile');assert.ok(row.expires_at>Date.now()&&row.expires_at<=Date.now()+600000);});
test('callbacks reject mismatched and expired states and consume cancelled states once',async()=>{const {env}=setup(),start=await authRoute(req('/auth/google'),env),url=new URL(start.headers.get('Location')),state=url.searchParams.get('state'),path='/auth/google/callback?error=access_denied&state='+state;assert.equal((await authRoute(req(path),env)).headers.get('Location'),'/?auth=invalid-state');const headers={Cookie:'__Host-nte-oauth='+state};assert.equal((await authRoute(req(path,headers),env)).headers.get('Location'),'/?auth=cancelled');assert.equal((await authRoute(req(path,headers),env)).headers.get('Location'),'/?auth=expired');assert.equal((await authRoute(req('/auth/google'),{})).status,503);});
test('Google identity verification rejects wrong audience, nonce and unverified email',async()=>{const {privateKey,publicKey}=await generateKeyPair('RS256');const claims={sub:'alice',email:'alice@example.test',email_verified:true,nonce:'nonce'};const sign=(overrides={},aud='test-client')=>new SignJWT({...claims,...overrides}).setProtectedHeader({alg:'RS256'}).setIssuer('https://accounts.google.com').setAudience(aud).setIssuedAt().setExpirationTime('5m').sign(privateKey);assert.deepEqual(await verifyGoogleToken(await sign(),'test-client','nonce',publicKey),{id:'google:alice',email:'alice@example.test'});await assert.rejects(async()=>verifyGoogleToken(await sign(),'test-client','wrong',publicKey));await assert.rejects(async()=>verifyGoogleToken(await sign({},'other'),'test-client','nonce',publicKey));await assert.rejects(async()=>verifyGoogleToken(await sign({email_verified:false}),'test-client','nonce',publicKey));await assert.rejects(async()=>verifyGoogleToken(await sign({nonce:'wrong'}),'test-client','nonce',publicKey));});
test('signout requires the same origin and revokes the server session',async()=>{const {db,env}=setup(),token='b'.repeat(64);db.prepare('INSERT INTO sessions VALUES (?,?,?,?)').run(await tokenHash(token),'alice','alice@example.test',Date.now()+60000);const headers={Cookie:'__Host-nte-session='+token,Origin:'https://evil.test'};assert.equal((await authRoute(req('/auth/signout',headers,'POST'),env)).status,403);headers.Origin='https://app.test';const res=await authRoute(req('/auth/signout',headers,'POST'),env);assert.equal(res.status,303);assert.match(res.headers.get('Set-Cookie'),/Max-Age=0/);assert.equal(db.prepare('SELECT COUNT(*) AS count FROM sessions').get().count,0);});
