import {tokenHash} from '../server/auth.js';
import {test} from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {DatabaseSync} from 'node:sqlite';import worker from '../server/worker.js';import {d1Adapter} from '../server/local-d1.mjs';import {parseSheet,parseCSV,identity} from '../public/feed.js';
const csv=fs.readFileSync('tests/fixtures/current.csv','utf8'),seed=JSON.parse(fs.readFileSync('public/tasks.json','utf8'));const settings={server:'europe',resetTime:'05:00',weekDay:1,biAnchor:'2026-10-08',seasonAnchor:'',confirmed:true};
function harness(){const db=new DatabaseSync(':memory:');for(const file of fs.readdirSync('drizzle').filter(f=>f.endsWith('.sql')))db.exec(fs.readFileSync('drizzle/'+file,'utf8'));const blobs=new Map();const env={DB:d1Adapter(db),AVATARS:{async put(k,v){blobs.set(k,v);},async get(k){const v=blobs.get(k);return v?{arrayBuffer:async()=>v.buffer}:null;},async delete(k){blobs.delete(k);}}};return async(path,who='alice',method='GET',data,origin='https://app.test')=>{const headers={};if(who){const token=Array.from(new TextEncoder().encode(who)).map(n=>n.toString(16).padStart(2,'0')).join('').padEnd(64,'0');db.prepare('INSERT INTO sessions(token_hash,user_id,email,expires_at) VALUES (?,?,?,?) ON CONFLICT(token_hash) DO NOTHING').run(await tokenHash(token),who,who+'@example.test',Date.now()+60000);headers.Cookie='__Host-nte-session='+token;}if(method!=='GET'){headers.Origin=origin;headers['Content-Type']='application/json';}const res=await worker.fetch(new Request('https://app.test'+path,{method,headers,body:data===undefined?undefined:JSON.stringify(data)}),env,{});return {status:res.status,data:await res.json()};};}
test('current spreadsheet retains all categories and removes only redundant currency entries',async()=>{const t=await parseSheet(csv,seed);assert.equal(t.length,62);assert.equal(new Set(t.map(x=>x.id)).size,62);assert.equal(t.filter(x=>x.category==='currency').length,26);assert.equal(t.find(x=>x.title==='Tycoon Incentive Fund').cycle,'once');assert.equal(t.reduce((n,x)=>n+x.guides.length,0),134);});
test('insertions, renamed linked tasks, and category moves retain activity identity',async()=>{const before=await parseSheet('Daily,Notes,Done\nAlpha,https://imgur.com/a/ABC123,false');const after=await parseSheet('Weekly,Notes,Done\nNew task,,false\nAlpha renamed,https://imgur.com/a/ABC123,false',before);assert.equal(after.length,2);assert.equal(after[1].id,before[0].id);assert.equal(after[1].category,'weekly');assert.equal(after[0].cycle,'weekly');});
test('future sections, one-time tags, explicit IDs and multiline notes are read',async()=>{const t=await parseSheet('Daily,Notes,Done\nFirst,"line one\nline two [id:stable]",FALSE\nOther Activities,Notes,Done\nNew activity,,FALSE\nMonthly,Notes,Done\nKeep forever (One time),,FALSE');assert.equal(t.length,3);assert.equal(t[0].notes,'line one\nline two');assert.equal(t[1].cycle,'once');assert.equal(t[2].cycle,'once');assert.equal(t[0].id,await identity('Renamed','','[id:stable]'));});
test('invalid spreadsheet fails rather than clearing the catalog',async()=>{await assert.rejects(()=>parseSheet('<html>Sign in</html>'));assert.throws(()=>parseCSV('"unfinished'));});
test('anonymous users cannot access account progress',async()=>{const api=harness();assert.equal((await api('/api/state',null)).status,401);});
test('two devices using the same account see the same checkbox; other users do not',async()=>{const api=harness();assert.equal((await api('/api/progress','alice','POST',{id:'nte-012345678901234567890123',done:true,period:'once',revision:0})).status,200);assert.equal((await api('/api/state')).data.entries['nte-012345678901234567890123'].done,true);assert.deepEqual((await api('/api/state','bob')).data.entries,{});});
test('stale device writes cannot overwrite the newer device state',async()=>{const api=harness(),entry={id:'nte-012345678901234567890123',done:true,period:'once',revision:0};await api('/api/progress','alice','POST',entry);await api('/api/progress','alice','POST',{...entry,done:false,revision:1});const conflict=await api('/api/progress','alice','POST',{...entry,revision:1});assert.equal(conflict.status,409);assert.equal(conflict.data.entry.done,false);assert.equal(conflict.data.entry.revision,2);});
test('imports are idempotent and never replace account progress',async()=>{const api=harness(),entry={id:'nte-012345678901234567890123',done:false,period:'once',revision:0};await api('/api/progress','alice','POST',entry);await api('/api/import','alice','POST',{settings,entries:[{...entry,done:true}]});const again=await api('/api/import','alice','POST',{settings,entries:[{...entry,done:true}]});assert.equal(again.data.entries[entry.id].done,false);assert.equal(again.data.entries[entry.id].revision,1);assert.equal(again.data.settings.server,'europe');});
test('settings are account-scoped and protected from stale overwrites',async()=>{const api=harness();await api('/api/settings','alice','POST',{settings,revision:0});assert.equal((await api('/api/settings','alice','POST',{settings:{...settings,server:'asia'},revision:0})).status,409);assert.equal((await api('/api/state','bob')).data.settings,null);});
test('cross-origin, malformed and user-ID injection writes are rejected or isolated',async()=>{const api=harness(),entry={id:'nte-012345678901234567890123',done:true,period:'once',revision:0,userId:'bob'};assert.equal((await api('/api/progress','alice','POST',entry,'https://evil.test')).status,403);assert.equal((await api('/api/progress','alice','POST',{...entry,done:'true'})).status,400);await api('/api/progress','alice','POST',entry);assert.deepEqual((await api('/api/state','bob')).data.entries,{});});

import {awardXP,levelInfo,cleanProfile,cleanLedger} from '../public/xp.js';
import {boundary} from '../public/reset.js';
test('XP awards once per reset, preserves one-time rewards and blocks schedule changes',()=>{const xp={},task={id:'nte-012345678901234567890123',cycle:'daily'},now=Date.parse('2026-10-06T12:00:00Z');assert.equal(awardXP(xp,task,settings,now),10);assert.equal(awardXP(xp,task,settings,now),0);assert.equal(awardXP(xp,task,{...settings,server:'asia',resetTime:'13:00'},now),0);assert.equal(awardXP(xp,task,settings,boundary('daily',settings,now).next),10);const once={id:'nte-112345678901234567890123',cycle:'once'};assert.equal(awardXP(xp,once,settings,now),220);assert.equal(awardXP(xp,once,settings,now+86400000*90),0);assert.equal(awardXP(xp,{...once,cycle:'daily'},settings,now+86400000*90),0);assert.equal(awardXP(xp,{id:'nte-212345678901234567890123',cycle:'season'},settings,now),0);});
test('levels increase exactly at their thresholds and backup validators reject unsafe photos',()=>{assert.equal(levelInfo({}).level,1);assert.equal(levelInfo({a:{xp:199,count:1}}).level,1);assert.deepEqual(levelInfo({a:{xp:200,count:1}}),{level:2,total:200,current:0,needed:400,percent:0,count:1});assert.equal(levelInfo({a:{xp:600,count:3}}).level,3);assert.throws(()=>cleanProfile({avatar:'data:image/svg+xml,<svg/>'}));assert.throws(()=>cleanLedger({x:{xp:Infinity}}));});
test('account XP ignores duplicate writes, unchecked tasks, forged periods and client points',async()=>{const api=harness();await api('/api/settings','alice','POST',{settings,revision:0});const task=(await parseSheet(csv,seed)).find(t=>t.cycle==='once');let entry={id:task.id,done:true,period:'once',revision:0,xp:999999};let r=await api('/api/progress','alice','POST',entry);assert.equal(r.data.xp[task.id].xp,220);r=await api('/api/progress','alice','POST',entry);assert.equal(r.status,409);assert.equal(r.data.xp[task.id].xp,220);await api('/api/progress','alice','POST',{...entry,revision:1,done:false});r=await api('/api/progress','alice','POST',{...entry,revision:2});assert.equal(r.data.xp[task.id].count,1);assert.deepEqual((await api('/api/state','bob')).data.xp,{});const daily=(await parseSheet(csv,seed)).find(t=>t.cycle==='daily');r=await api('/api/progress','alice','POST',{id:daily.id,done:true,period:'daily:0',revision:0});assert.equal(r.data.xp[daily.id],undefined);r=await api('/api/progress','alice','POST',{id:daily.id,done:true,period:boundary('daily',settings).key,revision:1});assert.equal(r.data.xp[daily.id].xp,10);});
test('profile updates are isolated and reject stale device revisions',async()=>{const api=harness();let r=await api('/api/profile','alice','POST',{profile:{name:'City Explorer',avatar:''},revision:0});assert.equal(r.data.profile.name,'City Explorer');assert.equal(r.data.profileRevision,1);r=await api('/api/profile','alice','POST',{profile:{name:'Stale',avatar:''},revision:0});assert.equal(r.status,409);assert.equal(r.data.profile.name,'City Explorer');assert.equal((await api('/api/state','bob')).data.profile.name,'Proxy');});
test('every repeating cadence earns again exactly at its reset',()=>{const now=Date.parse('2026-10-06T12:00:00Z');for(const [cycle,points] of Object.entries({daily:10,weekly:40,biweekly:90,monthly:160,season:200})){const xp={},task={id:'nte-012345678901234567890123',cycle},s={...settings,seasonAnchor:'2026-10-01'},next=boundary(cycle,s,now).next;assert.equal(awardXP(xp,task,s,now),points);assert.equal(awardXP(xp,task,s,next-1),0);assert.equal(awardXP(xp,task,s,next),points);assert.equal(xp[task.id].xp,points*2);}});
test('reimported backups preserve XP without adding it twice',async()=>{const api=harness(),id='nte-012345678901234567890123',xp={[id]:{xp:220,count:1,once:true,next:0,period:'once'}},data={entries:[],settings,xp};await api('/api/import','alice','POST',data);const twice=await api('/api/import','alice','POST',data);assert.equal(twice.data.xp[id].xp,220);assert.equal(twice.data.xp[id].count,1);assert.deepEqual((await api('/api/state','bob')).data.xp,{});});
test('private photos round-trip and cannot be overwritten by stale devices',async()=>{const api=harness(),avatar='data:image/jpeg;base64,/9j/2Q==';let r=await api('/api/profile','alice','POST',{profile:{name:'Proxy',avatar},revision:0});assert.equal(r.data.profile.avatar,avatar);assert.equal((await api('/api/state','bob')).data.profile.avatar,'');r=await api('/api/profile','alice','POST',{profile:{name:'Wrong',avatar},revision:0});assert.equal(r.status,409);assert.equal(r.data.profile.avatar,avatar);r=await api('/api/profile','alice','POST',{profile:{name:'Proxy',avatar:''},revision:1});assert.equal(r.data.profile.avatar,'');assert.equal((await api('/api/profile','alice','POST',{profile:{name:'Proxy',avatar:'data:image/jpeg;base64,YWJj'},revision:2})).status,400);});
