import {XP_POINTS,cleanProfile,cleanLedger} from '../public/xp.js';
import {boundary} from '../public/reset.js';
import {identity} from '../public/feed.js';
import {fetchSheet,REFRESH_MS} from '../public/feed.js';
import seed from '../public/tasks.json' with {type:'json'};
const json=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{'Content-Type':'application/json','Cache-Control':'private, no-store','X-Content-Type-Options':'nosniff'}});
function user(request){const id=request.headers.get('oai-authenticated-user-id'),email=request.headers.get('oai-authenticated-user-email');return id&&email?{id,email}:null;}
function sameOrigin(request){return request.headers.get('Origin')===new URL(request.url).origin&&request.headers.get('Sec-Fetch-Site')!=='cross-site';}
async function body(request){if(!request.headers.get('content-type')?.startsWith('application/json'))throw Error('JSON required');const text=await request.text();if(text.length>1000000)throw Error('Request too large');return JSON.parse(text);}
function validateEntry(e){if(!e||!/^(?:nte-[a-f0-9]{24}|(?:daily|weekly|biweekly|monthly|other|currency)-\d+)$/.test(e.id)||typeof e.done!=='boolean'||typeof e.period!=='string'||e.period.length>80||!Number.isSafeInteger(e.revision)||e.revision<0)throw Error('Invalid activity update');}
function validateSettings(s){if(!s||!['europe','america','asia'].includes(s.server)||!/^([01]\d|2[0-3]):[0-5]\d$/.test(s.resetTime)||!Number.isInteger(s.weekDay)||s.weekDay<0||s.weekDay>6)throw Error('Invalid reset settings');for(const key of ['biAnchor','seasonAnchor'])if(s[key]!==''&&(!/^\d{4}-\d{2}-\d{2}$/.test(s[key])||!Number.isFinite(Date.parse(s[key]+'T00:00:00Z'))))throw Error('Invalid reset date');return {server:s.server,resetTime:s.resetTime,weekDay:s.weekDay,biAnchor:s.biAnchor,seasonAnchor:s.seasonAnchor,confirmed:!!s.confirmed};}
async function readXP(db,id){const rows=await db.prepare('SELECT task_id,xp,count,period,next,once FROM awards WHERE user_id=?').bind(id).all();return Object.fromEntries(rows.results.map(r=>[r.task_id,{xp:r.xp,count:r.count,period:r.period,next:r.next,once:!!r.once}]));}
async function readState(db,id,avatars){const [p,s,profile,xp]=await Promise.all([db.prepare('SELECT task_id,done,period,revision,updated_at FROM progress WHERE user_id = ?').bind(id).all(),db.prepare('SELECT settings,revision FROM preferences WHERE user_id = ?').bind(id).first(),db.prepare('SELECT name,avatar,revision FROM profiles WHERE user_id=?').bind(id).first(),readXP(db,id)]);let avatar='';if(profile?.avatar){if(!avatars)throw Error('Photo storage unavailable');const object=await avatars.get(profile.avatar);if(object){const bytes=new Uint8Array(await object.arrayBuffer());avatar='data:image/jpeg;base64,'+btoa(String.fromCharCode(...bytes));}}return {entries:Object.fromEntries(p.results.map(x=>[x.task_id,{done:!!x.done,period:x.period,revision:x.revision,updatedAt:x.updated_at}])),settings:s?JSON.parse(s.settings):null,settingsRevision:s?.revision||0,profile:profile?{name:profile.name,avatar}:{name:'Proxy',avatar:''},profileRevision:profile?.revision||0,xp};}
let identifiedSeed;
async function xpTask(db,id){const cached=await db.prepare('SELECT payload FROM catalog WHERE id=?').bind('activities').first();if(cached)return JSON.parse(cached.payload).find(t=>t.id===id);identifiedSeed??=Promise.all(seed.map(async t=>({...t,id:await identity(t.title,t.url)})));return (await identifiedSeed).find(t=>t.id===id);}
export async function refreshCatalog(db,force=false){const old=await db.prepare('SELECT payload,updated_at FROM catalog WHERE id = ?').bind('activities').first();if(old&&Date.now()-old.updated_at<(force?30000:REFRESH_MS))return {tasks:JSON.parse(old.payload),updatedAt:old.updated_at};const previous=old?JSON.parse(old.payload):seed;try{const tasks=await fetchSheet(previous);const now=Date.now();await db.prepare('INSERT INTO catalog (id,payload,updated_at) VALUES (?,?,?) ON CONFLICT(id) DO UPDATE SET payload=excluded.payload,updated_at=excluded.updated_at').bind('activities',JSON.stringify(tasks),now).run();return {tasks,updatedAt:now};}catch(e){if(!old)throw e;return {tasks:previous,updatedAt:old.updated_at,stale:true,error:e.message};}}
async function gallery(album){if(!/^[a-zA-Z0-9]{3,20}$/.test(album))return json({error:'Invalid album'},400);const response=await fetch(`https://imgur.com/a/${album}/embed?pub=true`,{signal:AbortSignal.timeout(15000)});if(!response.ok)throw Error('Guide unavailable');const html=await response.text(),match=html.match(/var images\s*=\s*([\s\S]*?),\s*albumHash/);if(!match)throw Error('No guide images found');const data=JSON.parse(match[1]);return json({guides:data.images.slice(0,100).filter(i=>/^[a-zA-Z0-9]+$/.test(i.hash)&&/^\.(png|jpe?g|webp|gif)$/.test(i.ext)).map(i=>({src:`/api/image/${i.hash}${i.ext}`,description:String(i.description||'').slice(0,10000)}))});}
export default {async fetch(request,env,ctx){const url=new URL(request.url),path=url.pathname;
 if(!path.startsWith('/api/'))return env.ASSETS.fetch(request);
 try{
  const who=user(request);
  if(path==='/api/account'&&request.method==='GET')return json({user:who,hosting:true,storageAvailable:!!env.DB});
  if(path.startsWith('/api/guide/')&&request.method==='GET')return gallery(path.slice('/api/guide/'.length));
  if(path.startsWith('/api/image/')&&request.method==='GET'){const file=path.slice('/api/image/'.length);if(!/^[a-zA-Z0-9]+\.(png|jpe?g|webp|gif)$/.test(file))return json({error:'Invalid image'},400);const upstream=await fetch('https://i.imgur.com/'+file,{signal:AbortSignal.timeout(15000)});if(!upstream.ok||!upstream.headers.get('content-type')?.startsWith('image/'))return json({error:'Image unavailable'},502);return new Response(upstream.body,{headers:{'Content-Type':upstream.headers.get('content-type'),'Cache-Control':'public,max-age=86400','X-Content-Type-Options':'nosniff'}});}
  if(path==='/api/catalog'&&request.method==='GET'){if(!env.DB)return json({tasks:await fetchSheet(seed),updatedAt:Date.now()});return json(await refreshCatalog(env.DB));}
  if(path==='/api/catalog/refresh'&&request.method==='POST'){if(!sameOrigin(request))return json({error:'Same-origin request required'},403);if(!env.DB)return json({tasks:await fetchSheet(seed),updatedAt:Date.now()});const result=await refreshCatalog(env.DB,true);return json(result,result.stale?502:200);}
  if(!who)return json({error:'Sign in to sync your progress.'},401);
  if(!env.DB)return json({error:'Account storage is not available yet.'},503);
  if(path==='/api/state'&&request.method==='GET')return json(await readState(env.DB,who.id,env.AVATARS));
  if(request.method!=='POST'||!sameOrigin(request))return json({error:'Same-origin POST required'},403);
  const input=await body(request),now=Date.now();
  if(path==='/api/profile'){
   const profile=cleanProfile(input.profile);if(!Number.isSafeInteger(input.revision)||input.revision<0)throw Error('Invalid profile revision');
   const old=await env.DB.prepare('SELECT avatar FROM profiles WHERE user_id=?').bind(who.id).first();let key='';
   if(profile.avatar){if(!env.AVATARS)throw Error('Photo storage unavailable');const bytes=Uint8Array.from(atob(profile.avatar.split(',')[1]),c=>c.charCodeAt(0));if(bytes[0]!==255||bytes[1]!==216||bytes[2]!==255)throw Error('Invalid profile photo');key='avatars/'+crypto.randomUUID()+'.jpg';await env.AVATARS.put(key,bytes,{httpMetadata:{contentType:'image/jpeg'}});}
   const r=input.revision===0?await env.DB.prepare('INSERT INTO profiles(user_id,name,avatar,revision) VALUES (?,?,?,1) ON CONFLICT(user_id) DO NOTHING').bind(who.id,profile.name,key).run():await env.DB.prepare('UPDATE profiles SET name=?,avatar=?,revision=revision+1 WHERE user_id=? AND revision=?').bind(profile.name,key,who.id,input.revision).run();
   if(!r.meta.changes&&key)await env.AVATARS.delete(key);if(r.meta.changes&&old?.avatar&&env.AVATARS)await env.AVATARS.delete(old.avatar);
   return json(await readState(env.DB,who.id,env.AVATARS),r.meta.changes?200:409);
  }
  if(path==='/api/progress'){
   validateEntry(input);const task=await xpTask(env.DB,input.id);const pref=await env.DB.prepare('SELECT settings FROM preferences WHERE user_id=?').bind(who.id).first();const settings=pref?JSON.parse(pref.settings):null;
   const period=task&&settings?boundary(task.cycle,settings,now):null;
   const statements=[env.DB.prepare('INSERT INTO progress(user_id,task_id,done,period,revision,updated_at) SELECT ?,?,?,?,1,? WHERE ?=0 OR EXISTS(SELECT 1 FROM progress WHERE user_id=? AND task_id=? AND revision=?) ON CONFLICT(user_id,task_id) DO UPDATE SET done=excluded.done,period=excluded.period,revision=progress.revision+1,updated_at=excluded.updated_at WHERE progress.revision=?').bind(who.id,input.id,input.done?1:0,input.period,now,input.revision,who.id,input.id,input.revision,input.revision)];
   if(input.done&&period&&period.key!=='unconfigured'&&period.key===input.period&&XP_POINTS[task.cycle])statements.push(env.DB.prepare('INSERT INTO awards(user_id,task_id,xp,count,period,next,once) SELECT ?,?,?,1,?,?,? WHERE changes()=1 ON CONFLICT(user_id,task_id) DO UPDATE SET xp=awards.xp+excluded.xp,count=awards.count+1,period=excluded.period,next=excluded.next,once=excluded.once WHERE awards.once=0 AND awards.next<=? AND awards.period<>excluded.period').bind(who.id,input.id,XP_POINTS[task.cycle],period.key,period.next||0,task.cycle==='once'?1:0,now));
   const results=await env.DB.batch(statements);const row=await env.DB.prepare('SELECT done,period,revision,updated_at FROM progress WHERE user_id=? AND task_id=?').bind(who.id,input.id).first();return json({entry:row?{done:!!row.done,period:row.period,revision:row.revision,updatedAt:row.updated_at}:null,xp:await readXP(env.DB,who.id)},results[0].meta.changes?200:409);
  }
  if(path==='/api/settings'){const s=validateSettings(input.settings);if(!Number.isSafeInteger(input.revision)||input.revision<0)throw Error('Invalid settings revision');let r;if(input.revision===0)r=await env.DB.prepare('INSERT INTO preferences(user_id,settings,revision,updated_at) VALUES (?,?,1,?) ON CONFLICT(user_id) DO NOTHING').bind(who.id,JSON.stringify(s),now).run();else r=await env.DB.prepare('UPDATE preferences SET settings=?,revision=revision+1,updated_at=? WHERE user_id=? AND revision=?').bind(JSON.stringify(s),now,who.id,input.revision).run();return json(await readState(env.DB,who.id,env.AVATARS),r.meta.changes?200:409);}
  if(path==='/api/import'){if(!Array.isArray(input.entries)||input.entries.length>2000)throw Error('Invalid import');input.entries.forEach(validateEntry);const importedXP=cleanLedger(input.xp);const s=validateSettings(input.settings);const statements=input.entries.map(e=>env.DB.prepare('INSERT INTO progress(user_id,task_id,done,period,revision,updated_at) VALUES (?,?,?,?,1,?) ON CONFLICT(user_id,task_id) DO NOTHING').bind(who.id,e.id,e.done?1:0,e.period,now));for(const [id,a] of Object.entries(importedXP))statements.push(env.DB.prepare('INSERT INTO awards(user_id,task_id,xp,count,period,next,once) VALUES (?,?,?,?,?,?,?) ON CONFLICT(user_id,task_id) DO UPDATE SET xp=MAX(awards.xp,excluded.xp),count=MAX(awards.count,excluded.count),period=CASE WHEN excluded.next>awards.next THEN excluded.period ELSE awards.period END,next=MAX(awards.next,excluded.next),once=MAX(awards.once,excluded.once)').bind(who.id,id,a.xp,a.count,a.period,a.next,a.once?1:0));statements.unshift(env.DB.prepare('INSERT INTO preferences(user_id,settings,revision,updated_at) VALUES (?,?,1,?) ON CONFLICT(user_id) DO NOTHING').bind(who.id,JSON.stringify(s),now));for(let i=0;i<statements.length;i+=80)await env.DB.batch(statements.slice(i,i+80));return json(await readState(env.DB,who.id,env.AVATARS));}
  return json({error:'Not found'},404);
 }catch(e){return json({error:['Invalid','JSON','Request'].some(s=>e.message.startsWith(s))?e.message:'The update could not finish. Your last saved data is unchanged.'},/^(Invalid|JSON|Request)/.test(e.message)?400:503);}
 }};
